//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunCat.Strings {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunCat.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Old way.
        ///Calculates busy time of processors.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CounterType_Time_Description {
            get {
                return ResourceManager.GetString("CounterType_Time_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processor Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CounterType_Time_Title {
            get {
                return ResourceManager.GetString("CounterType_Time_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processor Counter Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CounterType_Title {
            get {
                return ResourceManager.GetString("CounterType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provides the same value as Task Manager on Windows 8+.
        ///Calculates actual performance of processors.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CounterType_Util_Description {
            get {
                return ResourceManager.GetString("CounterType_Util_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processor Utilization과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CounterType_Util_Title {
            get {
                return ResourceManager.GetString("CounterType_Util_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exit_Title {
            get {
                return ResourceManager.GetString("Exit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Runner_Item_Cat_Title {
            get {
                return ResourceManager.GetString("Runner_Item_Cat_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horse과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Runner_Item_Horse_Title {
            get {
                return ResourceManager.GetString("Runner_Item_Horse_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parrot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Runner_Item_Parrot_Title {
            get {
                return ResourceManager.GetString("Runner_Item_Parrot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Runner과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Runner_Title {
            get {
                return ResourceManager.GetString("Runner_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpeedLimit_Default_Title {
            get {
                return ResourceManager.GetString("SpeedLimit_Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Runner Speed Limit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpeedLimit_Title {
            get {
                return ResourceManager.GetString("SpeedLimit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run at startup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Startup_Title {
            get {
                return ResourceManager.GetString("Startup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Theme_Dark_Title {
            get {
                return ResourceManager.GetString("Theme_Dark_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Theme_Default_Title {
            get {
                return ResourceManager.GetString("Theme_Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Theme_Light_Title {
            get {
                return ResourceManager.GetString("Theme_Light_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Theme_Title {
            get {
                return ResourceManager.GetString("Theme_Title", resourceCulture);
            }
        }
    }
}
